#ifndef LV_CONF_H
#define LV_CONF_H

/* PC simulator LVGL v9.2.2 config - matches STM32 target (RGB565, 480x320)
   but enables Windows backend for desktop simulation. */

#include <stdint.h>

/* Color depth - same as target ST7796 panel */
#define LV_COLOR_DEPTH                  16

/* Memory - PC has plenty, use 4MB */
#define LV_USE_STDLIB_MALLOC            LV_STDLIB_BUILTIN
#define LV_USE_STDLIB_STRING            LV_STDLIB_BUILTIN
#define LV_USE_STDLIB_SPRINTF           LV_STDLIB_BUILTIN
#define LV_MEM_SIZE                     (4U * 1024U * 1024U)

/* OS - Windows backend for PC simulator */
#define LV_USE_OS                       LV_OS_WINDOWS

/* Drawing */
#define LV_DRAW_SW_DRAW_UNIT_CNT        1
#define LV_USE_DRAW_SW_COMPLEX_GRADIENTS 1

/* Logging - enable for simulator debugging */
#define LV_USE_LOG                      1
#define LV_LOG_LEVEL                    LV_LOG_LEVEL_WARN
#define LV_LOG_PRINTF                   1
#define LV_USE_ASSERT_NULL              1
#define LV_USE_ASSERT_MALLOC            1
#define LV_USE_ASSERT_STYLE             0
#define LV_USE_ASSERT_MEM_INTEGRITY     0
#define LV_USE_ASSERT_OBJ               0

/* Monitors */
#define LV_USE_PERF_MONITOR             0
#define LV_USE_MEM_MONITOR              0

/* Fonts - match target config */
#define LV_FONT_MONTSERRAT_12           1
#define LV_FONT_MONTSERRAT_14           1
#define LV_FONT_MONTSERRAT_16           1
#define LV_FONT_MONTSERRAT_18           1
#define LV_FONT_MONTSERRAT_20           1
#define LV_FONT_MONTSERRAT_24           1
#define LV_FONT_MONTSERRAT_28           1
#define LV_FONT_DEFAULT                 &lv_font_montserrat_16

/* Theme & Layout */
#define LV_USE_THEME_DEFAULT            1
#define LV_USE_FLEX                     1
#define LV_USE_GRID                     1

/* Widgets - enable all for simulator */
#define LV_USE_ARC                      1
#define LV_USE_BAR                      1
#define LV_USE_BUTTON                   1
#define LV_USE_BUTTONMATRIX             1
#define LV_USE_CALENDAR                 1
#define LV_USE_CANVAS                   1
#define LV_USE_CHART                    1
#define LV_USE_CHECKBOX                 1
#define LV_USE_DROPDOWN                 1
#define LV_USE_IMAGE                    1
#define LV_USE_IMGBTN                   1
#define LV_USE_KEYBOARD                 1
#define LV_USE_LABEL                    1
#define LV_USE_LED                      1
#define LV_USE_LINE                     1
#define LV_USE_LIST                     1
#define LV_USE_MENU                     1
#define LV_USE_MSGBOX                   1
#define LV_USE_ROLLER                   1
#define LV_USE_SCALE                    1
#define LV_USE_SLIDER                   1
#define LV_USE_SPAN                     1
#define LV_USE_SPINBOX                  1
#define LV_USE_SPINNER                  1
#define LV_USE_SWITCH                   1
#define LV_USE_TEXTAREA                 1
#define LV_USE_TABLE                    1
#define LV_USE_TABVIEW                  1
#define LV_USE_TILEVIEW                 1
#define LV_USE_WIN                      1

/* Runtime TTF loading is disabled for the boot animation. */
#define LV_USE_TINY_TTF                 0

/* Windows display driver */
#define LV_USE_WINDOWS                  1

/* Demos - disabled */
#define LV_USE_DEMO_WIDGETS             0
#define LV_USE_DEMO_BENCHMARK           0
#define LV_USE_DEMO_STRESS              0
#define LV_USE_DEMO_MUSIC               0


/* CJK fonts (SimHei, generated by lv_font_conv) */
#define LV_FONT_CJK_12                 1
#define LV_FONT_CJK_14                 1
#define LV_FONT_CJK_18                 1
#define LV_FONT_CJK_20                 1
#define LV_FONT_CJK_28                 1

#endif /* LV_CONF_H */
